### ISSUE TITLE
org.json.JSONException: No value for success

### ISSUE THREAD

**Issue by Khaos116** [TKaxv-7S/XQuickEnergy#86]
### 程序版本 / 框架版本 / 模块版本

1.2.5-test18-TK

### 系统版本 / Android版本

Android 14

### 详细描述问题发生的具体原因

建议使用
jo.optBoolean("success")
替代
jo.getBoolean("success")
防止没有响应值出现闪退

### 提供模块问题 Log 或必要 Log

13:14:28.544 I/ERROR: KBMember, org.json.JSONException: No value for success
 at org.json.JSONObject.get(JSONObject.java:398)
 at org.json.JSONObject.getBoolean(JSONObject.java:419)
 at pansong291.xposed.quickenergy.task.model.kbMember.KBMember.lambda$init$0(Unknown Source:11)
 at pansong291.xposed.quickenergy.task.model.kbMember.KBMember.c(Unknown Source:0)
 at pansong291.xposed.quickenergy.hook.a.run(Unknown Source:14)
 at java.lang.Thread.run(Thread.java:1012)

**Comment by Khaos116** [comment]
另外还发现了一个空指针的问题：
ApplicationHook类下面
lastExecTimeCalendar和nextExecTimeCalendar
调用compareTo时，出现了空指针的bug

**Comment by TKaxv-7S** [comment]
这些问题正式版 v1.2.5-TK 都已修复，请前往新仓库 [Sesame-TK](https://github.com/TKaxv-7S/Sesame-TK) 更新
